name: m100-build
description: Build Model 100 artifacts using the npm CLI
inputs:
  cli-package:
    description: NPM package name for the CLI
    required: false
    default: "@m100/cli"
  source:
    description: Path to .DO source
    required: true
  base:
    description: Base address (hex, no 0x)
    required: false
    default: "8001"
  out-dir:
    description: Output directory
    required: false
    default: "dist"
  ascii-name:
    description: Output name for packed .DO (optional; defaults to source basename)
    required: false
  tokenized-name:
    description: Output name for .BA (optional; defaults to ascii-name with .DO -> .BA)
    required: false
  lint:
    description: Run m100 lint on source before building
    required: false
    default: "true"
outputs:
  ascii-path:
    description: Path to packed .DO output
    value: ${{ steps.build.outputs.ascii-path }}
  tokenized-path:
    description: Path to tokenized .BA output
    value: ${{ steps.build.outputs.tokenized-path }}
runs:
  using: composite
  steps:
    - name: Install CLI
      shell: bash
      run: npm install -g "${{ inputs.cli-package }}"
    - name: Lint source
      if: ${{ inputs.lint == 'true' }}
      shell: bash
      run: m100 lint "${{ inputs.source }}"
    - name: Build artifacts
      id: build
      shell: bash
      run: |
        set -euo pipefail
        source="${{ inputs.source }}"
        ascii_name="${{ inputs.ascii-name }}"
        token_name="${{ inputs.tokenized-name }}"

        if [ -z "$ascii_name" ]; then
          ascii_name="$(basename "$source")"
        fi

        if [ -z "$token_name" ]; then
          token_name="$(echo "$ascii_name" | sed -E 's/\.[dD][oO]$/.BA/')"
          if [ "$token_name" = "$ascii_name" ]; then
            token_name="${ascii_name}.BA"
          fi
        fi

        ascii_dir="${{ inputs.out-dir }}/ascii_packed"
        token_dir="${{ inputs.out-dir }}/tokenized_packed"
        mkdir -p "$ascii_dir" "$token_dir"

        ascii_path="$ascii_dir/$ascii_name"
        token_path="$token_dir/$token_name"

        work_dir="$(mktemp -d)"
        trap 'rm -rf "$work_dir"' EXIT

        squash_path="$work_dir/squash.DO"
        renumber1_path="$work_dir/renumber1.DO"
        pack_path="$work_dir/pack.DO"

        m100 squash "$source" --out "$squash_path"
        m100 renumber "$squash_path" --start 1 --increment 1 --out "$renumber1_path"
        m100 pack "$renumber1_path" --out "$pack_path"
        m100 renumber "$pack_path" --start 1 --increment 1 --out "$ascii_path"

        if [ "${{ inputs.lint }}" = "true" ]; then
          m100 lint "$ascii_path"
        fi

        m100 tokenize "$ascii_path" --out "$token_path" --base "${{ inputs.base }}"

        echo "ascii-path=$ascii_path" >> "$GITHUB_OUTPUT"
        echo "tokenized-path=$token_path" >> "$GITHUB_OUTPUT"
